name: money_expense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  meta: ^1.16.0
  go_router: ^16.2.1
  sqflite: ^2.4.2
  equatable: ^2.0.7
  path: ^1.9.1
  syncfusion_flutter_datepicker: ^31.1.19
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/json/
